# Generated by Django 5.2.8 on 2025-11-21 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_filme_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='telefone',
            new_name='nome',
        ),
    ]
